python train.py --train \
  --model-id gvp_l6_k10_s100_no_esm2 \
  --train-path ../data/cleaned_skip_missing/train \
  --val-path ../data/cleaned_skip_missing/val \
  --test-path ../data/cleaned_skip_missing/test \
  --max-nodes 3000 \
  --num-workers 6 \
  --gnn-layers 6 \
  --top-k 10 \
  --node-h-scalar-dim 100 \
  --lr 1e-3